main: me.d3x.grandexchange.GrandExchange
name: GrandExchange
version: 1.0
author: OverlySalty
description: Player-to-Player exchange service based off of the RuneScape Grand Exchange
commands:
  ge:
    description: opens Grand Exchange interface
    usage: /ge